### ISSUE TITLE
Holding a key using Actions doesn`t work

### ISSUE THREAD

**Issue by Elven1291** [MachinePublishers/jBrowserDriver#153] opened 2016-07-08 07:09 UTC
When trying to simulate user holding down CTRL key and clicking on a list of items to select\unselect multipe values, I have found that JBrowserDriver does not register CTRL key being held. It means that mouse click happens, but it doesn`t select\unselect item from the list

Code to reproduce issue:

```java
//headless browser init
DesiredCapabilities capabilities = new DesiredCapabilities("jbrowserdriver", "1", Platform.ANY);
capabilities.merge(Settings.builder().buildCapabilities());
WebDriver driver = new JBrowserDriver(capabilities);
driver.get("http://demoqa.com/selectable/");
//Action itself
Actions actions = new Actions(driver);
/* selectedItemsListDefaultView is a PageObject field initiated by PageFactory and auto refreshed when it is called.
It contains list of selected items.
Its xpath is -> ".//*[@id='selectable']/li[contains(@class,'ui-selected')]" */
Code below tries to unselect all selected items.
while (selectedItemsListDefaultView.size() != 0) {
           actions.keyDown(Keys.CONTROL).perform();
            for (WebElement item : selectedItemsListDefaultView) {
                item.click();
            }
           actions.keyUp(Keys.CONTROL).perform();
        }
```

On screenshot below you can see the same page in Chrome. Orange items in list are selected, white ones are not. 
![image](https://cloud.githubusercontent.com/assets/20340000/16679726/7f878888-44f2-11e6-9e1d-458d5b58d83d.png)

**Comment by hollingsworthd** [comment] 2016-07-09 13:44
I think this is a duplicate of #148. Regardless, thanks for the info and test example! Refer to #148 for status on this issue.

**Closed by hollingsworthd** 2016-07-09 13:44 UTC
