### ISSUE TITLE
302 Redirect causes authentication not to be passed

### ISSUE THREAD

**Issue by vrosu** [MachinePublishers/jBrowserDriver#36] opened 2016-02-09 13:25 UTC
I have a strange authentication cycle, which happens like this:

1. In browser, I do first a https://localhost:8443/globalSite/site1/name?urlParam1=2cdd2b2a-35e7-427a-9d04-eab13741368e&urlParam2=true
**Request headers are:**
Host: localhost:8443
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36
Accept-Encoding: gzip, deflate, sdch

2. Then, the request redirect to a subsite of the same domain, while setting a Session valid for all the global domain, see below

**Response headers are:**
HTTP/1.1 302 Found
Server: Apache-Coyote/1.1
X-FRAME-OPTIONS: SAMEORIGIN
Set-Cookie: JSESSIONID=FDCCA8754CC613C6BDAEBE7C7A7886C5; Path=/globalSite/; Secure; HttpOnly
Expires: 0
Cache-Control: no-store, no-cache
Cache-Control: post-check=0, pre-check=0
Pragma: no-cache
Location: https://localhost:8443/globalSite/site2/index.html#param=name&urlParam1=2cdd2b2a-35e7-427a-9d04-eab13741368e&urlParam2=true
Content-Type: text/html;charset=UTF-8
Content-Length: 0
Date: Tue, 09 Feb 2016 12:50:13 GMT

While using the 0.8.6 version I can't achieve this functionality, because I think the Session cookie is not set to subsequent requests (?).

The strange thing is that if I try to access directly the redirect link, https://localhost:8443/globalSite/site2/index.html#param=name&urlParam1=2cdd2b2a-35e7-427a-9d04-eab13741368e&urlParam2=true this won't work, because the authentication is only done on the initial request.
If I try to access in a private window the second request, the Form Basic authentication dialogue comes on.

Should I do a complete log for that?

**Comment by hollingsworthd** [comment] 2016-02-09 21:06
I tried to reproduce this (no luck), adding this test: https://github.com/MachinePublishers/jBrowserDriver/commit/9549973a657df74e4f2ccc8357e74b8b8c38b89d ... not sure if I've simplified the test case too much to reproduce it.

In the last day I did fix some other seemingly unrelated issues. Can you upgrade to 0.8.7 and then provide log output, with trace and wire logging enabled? Also in your own debugging don't forget URL fragments are not sent to the server (#param=...)

**Comment by hollingsworthd** [comment] 2016-02-09 21:08
Wire logging will capture full responses including body content. Either clip those or send via email if you prefer.

**Comment by hollingsworthd** [comment] 2016-02-14 06:44
Closing for now since I can't reproduce this. If you can provide requested info, please re-open. Thanks.

**Closed** 2016-02-14 06:45 UTC
Labels: bug, wontfix
