### ISSUE TITLE
Unexpected content at the end of chunk

### ISSUE THREAD

**Issue by Sawyer4** [MachinePublishers/jBrowserDriver#214] opened 2016-10-22 15:18 UTC
Hello,

I have this exception :
`[org.apache.http.wire] : http-outgoing-0 << "[0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][\n]"
[org.apache.http.wire] : http-outgoing-0 << "[0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9]<option value="LS">LESOTHO</option>[\n]"
 [org.apache.http.wire] : http-outgoing-0 << "[0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][\n]"
 [org.apache.http.wire] : http-outgoing-0 << "[0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9]<option value="LV">LETTONIE</option>[\n]"
[org.apache.http.wire] : http-outgoing-0 << "[0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][\n]"

org.apache.http.MalformedChunkCodingException: Unexpected content at the end of chunk
at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:259)
 [org.apache.http.wire] : http-outgoing-0 << "[0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9]<option value="LB">LIBAN</option>[\n]"
    at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:227)
    at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:186)
    at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
    at com.machinepublishers.jbrowserdriver.Util.toBytes(Util.java:99)
    at com.machinepublishers.jbrowserdriver.ResponseHandler.handleResponse(ResponseHandler.java:52)
    at com.machinepublishers.jbrowserdriver.StreamConnection.getInputStream(StreamConnection.java:402)
    at com.sun.webkit.network.URLLoader.receiveResponse(URLLoader.java:501)
    at com.sun.webkit.network.URLLoader.doRun(URLLoader.java:163)
    at com.sun.webkit.network.URLLoader.lambda$run$91(URLLoader.java:128)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.webkit.network.URLLoader.run(URLLoader.java:127)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
 [org.apache.http.wire] : http-outgoing-0 << "[0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][0x9][\n]"`

It occurs when i'm sending a form. After the ".submit()" call i have this exception and the getPageSource() is empty.

It's blocking my code.
Do you have an idea about a solution ?

My code to submit: `multiParcelRecipientForm = client.client.findElement(By.xpath("//form[@name='multicolisForm']"));
        multiParcelRecipientForm.submit();`

Best regards,

**Comment by hollingsworthd** [comment] 2016-11-05 05:01
I suspect this is a duplicate of #124. Regardless this report will be useful; thanks!

**Closed by hollingsworthd** 2016-11-05 05:01 UTC
