### ISSUE TITLE
Problem getting body element with jBrowserDriver

### ISSUE THREAD

**Issue by PatrickHuetter** [MachinePublishers/jBrowserDriver#51] opened 2016-03-01 14:51 UTC
My software is able to use different webdrivers for example ghostdriver, chromedriver, firefoxdriver and so on. In one part of the software, i'm calling a simple json endpoint to get some information about the current request (like httpbin.org). This works fine with all webdrivers except jBrowserDriver.

The code:
```
            WebElement body = this.webDriver.findElement(By.tagName("body"));
            String jsonTxt = body.getText();
```
It fails because _body_ is null (NullPointerException).

Using ```this.webDriver.getPageSource()``` i get the correct pagesource as string.
```
<html><head></head><body>{"ip":"xxx.xxx.74.xx4","headers":{"Host":"domain.tld","User-Agent":"Mozilla\/5.0 (Windows NT 6.1; rv:38.0) Gecko\/20100101 Firefox\/38.0","Accept":"text\/html,application\/xhtml+xml,application\/xml;q=0.9,*\/*;q=0.8","Accept-Language":"en-us,en;q=0.5","Accept-Encoding":"gzip, deflate","Dnt":"1","Connection":"keep-alive"}}</body></html>
```

Why does jBrowserDriver fail to find the body element?

**Comment by hollingsworthd** [comment] 2016-03-01 17:52
Can you provide a test case? Trying this works for me:

```java
    JBrowserDriver driver = new JBrowserDriver();
    driver.get("http://httpbin.org/get");
    System.out.println(driver.findElement(By.tagName("body")).getText());

**Comment by hollingsworthd** [comment] 2016-03-01 18:03
I tried the above test in v0.10.1 but this may be fixed in Master by https://github.com/MachinePublishers/jBrowserDriver/commit/118620708a756a7e99f3de7137887a17f29387c8 which handles responses sent as attachments... there are some other changes to that might help. Next release will be out within days.

**Comment by PatrickHuetter** [comment] 2016-03-03 13:03
I'm also using version 0.10.1. I can't provide a test case because the endpoint isn't public. What i can say is that the webserver response is plain json as text without any html but i've to use ```driver.findElement(By.tagName("body")).getText()``` because the json occurs within html using webdriver. I'll test it with the next release. Thank you!

**Comment by PatrickHuetter** [comment] 2016-03-03 14:42
To be more precisely, the exception i get seems to be this one:
```
[Port 10000] [2016-03-03T15:37:03+0100] [WARNING] java.rmi.UnmarshalException: error unmarshalling return; nested exception is: 
15:37:03.130 [CrawlingWorker] INFO  com.executor.services.TaskManagerService - Removed task in work successfully from tasksInWorkRateLimited list.
[Port 10000] 	java.io.EOFException
15:37:03.130 [CrawlingWorker] INFO  com.executor.services.TaskManagerService - Adding 1 tasks.
[Port 10000] 	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:193)
[Port 10000] 	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:194)
[Port 10000] 	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:148)
[Port 10000] 	at com.machinepublishers.jbrowserdriver.$Proxy21.findElement(Unknown Source)
[Port 10000] 	at com.machinepublishers.jbrowserdriver.JBrowserDriver.findElement(JBrowserDriver.java:498)
[Port 10000] 	at com.executor.worker.CrawlingWorker.isBehindProxyAndRequestHeadersAreOK(CrawlingWorker.java:785)
[Port 10000] 	at com.executor.worker.CrawlingWorker.run(CrawlingWorker.java:125)
[Port 10000] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[Port 10000] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[Port 10000] 	at java.lang.Thread.run(Thread.java:745)
[Port 10000] Caused by: java.io.EOFException
[Port 10000] 	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2601)
[Port 10000] 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1319)
[Port 10000] 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
[Port 10000] 	at sun.rmi.server.UnicastRef.unmarshalValue(UnicastRef.java:326)
[Port 10000] 	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:175)
[Port 10000] 	... 9 more
[Port 10000] 
java.lang.NullPointerException
```

**Comment by hollingsworthd** [comment] 2016-03-29 04:21
I can't reproduce this. Let me know if it's still a problem. If so, turn on [wire logging](http://machinepublishers.github.io/jBrowserDriver/com/machinepublishers/jbrowserdriver/Settings.Builder.html#wireConsole-boolean-) and let me know relevant headers or response content so I can create a test case.

**Closed by hollingsworthd** 2016-03-29 04:21 UTC
Labels: bug, wontfix
