### ISSUE TITLE
Error initializing QuantumRenderer: no suitable pipeline found (CentOS)

### ISSUE THREAD

**Issue by oahzuw** [MachinePublishers/jBrowserDriver#18] opened 2016-01-14 08:49 UTC
ubuntu 14.04 test success
but 
Distributor ID: CentOS
Description:    CentOS release 5.8 (Final)
Can't run !

java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
Graphics Device initialization failed for :  sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:221)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:205)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$156(LauncherImpl.java:182)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        ... 1 more
[2016-01-14T07:58:14+0800] [WARNING] com.machinepublishers.browser.Browser$Fatal: Method call failed: launch
        at com.machinepublishers.jbrowserdriver.JavaFxObjectServer.call(JavaFxObjectServer.java:163)
        at com.machinepublishers.jbrowserdriver.JavaFxObject.call(JavaFxObject.java:72)
        at com.machinepublishers.jbrowserdriver.SettingsManager$1.run(SettingsManager.java:50)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.machinepublishers.jbrowserdriver.JavaFxObjectServer.call(JavaFxObjectServer.java:104)
        ... 3 more
Caused by: java.lang.RuntimeException: No toolkit found

**Comment by oahzuw** [comment] 2016-01-14 10:03
Already installed libgtk-java.x86_64  libswt3-gtk2.x86_64 , Still can not run

**Comment by hollingsworthd** [comment] 2016-01-14 13:03
Also try installing  libXtst.x86_64

**Comment by hollingsworthd** [comment] 2016-01-15 08:39
Also, I don't think this lib is required but I know it pulls in the proper transitive dependencies: webkitgtk.x86_64

I'll get better instructions for CentOS at some point. But if you install both libXtst.x86_64 and webkitgtk.x86_64 it should work.

**Comment by oahzuw** [comment] 2016-01-16 06:51
I tried, but can't run

**Comment by hollingsworthd** [comment] 2016-01-19 06:09
Are you on CentOS 6 or 7?

Can you add this options to the java command and let me know the output? "-Dprism.verbose=true" ... e.g., java -Dprism.verbose=true -jar somejar.jar

**Comment by hollingsworthd** [comment] 2016-02-12 09:33
I can't reproduce this. Need more info to proceed. Closing for now...

**Closed by hollingsworthd** 2016-02-12 09:33 UTC
Labels: bug
