### ISSUE TITLE
[Port 10000] Error: Could not find or load main class com.machinepublishers.jbrowserdriver.JBrowserDriverServer on MAC OSX with jetty server maven plugin

### ISSUE THREAD

**Issue by MartinKuzdowicz** [MachinePublishers/jBrowserDriver#41] opened 2016-02-17 12:38 UTC
I am using JBrowserDriver on mac osx and i run my application on jetty maven plugin. 
I am using maven and 0.9.1 version of JBrowserDriver
 JBrowserDriver and selenium works fine when i run it as java application but it fails with error when i run it on server. It works with firefox driver on jetty server for example.
error message:
[Port 10000] Error: Could not find or load main class com.machinepublishers.jbrowserdriver.JBrowserDriverServer

**Comment by hollingsworthd** [comment] 2016-02-17 20:31
Thanks. This will be part of v0.9.2 release today/tomorrow.

**Comment by vrosu** [comment] 2016-02-19 12:35
I just used the 0.9.2 version from a Tomcat app server and it still gives the [Port 11000] Error: Could not find or load main class com.machinepublishers.jbrowserdriver.JBrowserDriverServer

**Comment by hollingsworthd** [comment] 2016-02-19 17:03
@vrosu, I can't reproduce this. Can you let me know the layout of your WAR and what versions of Tomcat and Java you're using? If you happen to have an example WAR to attach here and source that would be great. Thanks.

**Comment by hollingsworthd** [comment] 2016-02-24 01:52
If anyone still has this bug please help me reproduce it. Otherwise I think it's fixed. Closing issue...

**Comment by Xryaznov** [comment] 2016-02-24 11:41
I've got the same error when building jar file with maven-assembly-plugin on Windows 7x64. I can invite you to my Bitbucket rep.

**Comment by hollingsworthd** [comment] 2016-02-24 16:55
@Xryaznov that would be great. Thanks

**Comment by hollingsworthd** [comment] 2016-02-25 06:18
@Xryaznov unfortunately I couldn't reproduce this. It may be fixed though in the now released v0.10.1, as I'm using https://github.com/lukehutch/fast-classpath-scanner/ to get the classpath.

Can you see if the problem still exists? If so, do you just run this from command line or is it on an app server? What java version? Thanks

**Comment by Xryaznov** [comment] 2016-02-25 09:38
I confirm no issue exists in v0.10.1, at least for my case, thank you.

**Comment by mateusz-gorski-hello** [comment] 2016-03-10 09:31
I want to report that I am using `v0.10.1` version and I get the error 

`[Port 10000] Error: Could not find or load main class com.machinepublishers.jbrowserdriver.JBrowserDriverServer`

**Comment by hollingsworthd** [comment] 2016-03-10 09:37
@mateusz-gorski-hello can you provide more info about how you're running the app, building the jar, your tech stack, etc?

**Comment by mateusz-gorski-hello** [comment] 2016-03-10 09:40
I am trying to use it as `RemoteWebDriver` . I added the lib to my `sbt` dependencies , I can see it cached under `~/.ivy2` folder .

**Comment by hollingsworthd** [comment] 2016-03-10 09:58
I've never tested this with Scala and at this point it's not supported. I'm available for paid support and also happy to accept pull requests. The issue is this spawns a separate Java process and needs to build up the classpath for it dynamically from the current runtime classpath: https://github.com/MachinePublishers/jBrowserDriver/blob/master/src/com/machinepublishers/jbrowserdriver/JBrowserDriver.java#L131

**Comment by hollingsworthd** [comment] 2016-03-10 10:12
@mateusz-gorski-hello as a workaround, Selenium Server would probably work. It has bindings for many languages and you can use JBrowserDriver with it.

**Comment by mateusz-gorski-hello** [comment] 2016-03-10 10:34
I use `PhantomJS` and it works prefectly but lib hasn't been updated in a long time. I guess I will stick with it.

**Comment by gmalouf** [comment] 2016-04-06 03:39
I can confirm that I get this error trying to use the driver from the play framework 2.4.x (Scala).

**Comment by 5hawnknight** [comment] 2016-04-09 20:45
I had the same issue on ubuntu 15.10 then installed these three libs and their dependencies.
libgtk-3-dev 
libswt-gtk-3-java 
libxslt1-dev

**Comment by hollingsworthd** [comment] 2016-04-10 01:30
Thanks for the info @5hawnknight... I might add that to the readme

**Comment by hollingsworthd** [comment] 2016-05-11 00:35
Updated install instructions are in the readme now. I tried this on ScalaTest Play and it works.

**Closed by hollingsworthd** 2016-05-11 00:35 UTC
Labels: bug

**Comment by oschrenk** [comment] 2016-06-06 18:48
This error was still happening in a very simple sbt/scala project for me and @hollingsworthd had the right idea that something was wrong with the classpath. The issue is fixed in HEAD of lukehutch/fast-classpath-scanner for me. See also: https://github.com/lukehutch/fast-classpath-scanner/issues/51

**Comment by lukehutch** [comment] 2016-06-06 18:50
Thanks for the cross-link. I'll be pushing out a new release of FastClasspathScanner containing the fix in the next couple of days, then this should be fixed once you update this project to depend on the latest version.

**Comment by oschrenk** [comment] 2016-06-06 18:51
When you cut a new release, I'll do a PR in the other project to bump the version and move the package around.

Thanks!

**Comment by sasajib** [comment] 2016-06-08 18:35
I was having this problem. But I found solution for scala projects. In build.sbt file add this line 

`fork in run := true`

**Comment by hollingsworthd** [comment] 2016-06-09 12:31
jBrowserDriver v0.14.5 includes the latest FastClasspathScanner. Thanks, Luke, it's a very useful project!

**Comment by serlesen** [comment] 2016-11-10 10:50
Hello, I'm using jBrowserDriver v0.14.7 used with spring-boot; and when it calls
> List<File> items = new ClasspathFinder().getUniqueClasspathElements();

I've the war file used, which is filtered by
> if (curItem.isFile() && curItem.getPath().endsWith(".jar")) {

and the inner dependencies of the war files are not taken into account when building the jar file with the MANIFEST.MF, which lead to a
> Error: Could not find or load main class com.machinepublishers.jbrowserdriver.JBrowserDriverServer

when launching the process as
> java -classpath /tmp/jbd_classpath_4315802091211828452/classpath.jar -Djava.io.tmpdir=/tmp/jbd_tmp_1749246194792175469 -Djava.rmi.server.hostname=127.0.0.1 com.machinepublishers.jbrowserdriver.JBrowserDriverServer -1 -2 -3

**Comment by lukehutch** [comment] 2016-11-10 11:26
@serlesen: Are the inner dependencies of the war file contained in the list returned by `new ClasspathFinder().getUniqueClasspathElements()`? If not, it is a bug in FastClasspathScanner -- please file a bug there. (You can call `.verbose` before `.getUniqueClasspathElements()` for extra log output.)

I'm only taking a guess, but if the inner dependencies are contained in that list, it's possible that the inner dependency paths contain a `!` character to separate jarfile path from the path within the jar, and when the jar file is built, the complete filename is used as a `File` path (rather than a URL), which would result in a `FileNotFoundException`, causing the resource not to be copied into the built jar.

**Comment by lukehutch** [comment] 2016-11-10 11:29
PS @serlesen / @hollingsworthd there have been a few bugfix releases for FastClasspathScanner in the last few months and it seems pretty stable now -- you should update the version used by jBrowserDriver if you haven't done so recently. (Also @serlesen please update your version before reporting, if it looks like the bug is in FastClasspathScanner and not jBrowserDriver.)

**Comment by serlesen** [comment] 2016-11-10 14:12
@lukehutch tanks for the reply. The current version (v0.17.0) doesn't solve the problem neither. The `new FastClasspathScanner().getUniqueClasspathElements()` only returns the war files, no inner dependencies. I will report this to FastClasspathScanner.

**Comment by lukehutch** [comment] 2016-11-10 17:31
@serlesen Thanks, will take a look. Please add the verbose log output to your bug report, and ideally if it's not clear what's going on from the logs, it would be great if you could provide instructions to reproduce, or a minimal testcase. Thanks! https://github.com/lukehutch/fast-classpath-scanner/issues/new
