### ISSUE TITLE
NoSuchMethodException: com.sun.webkit.dom.HTMLDocumentImpl.call(java.lang.String, [Ljava.lang.Object;)

### ISSUE THREAD

**Issue by chakrayadavalli** [MachinePublishers/jBrowserDriver#9] opened 2015-11-21 10:22 UTC
Hi,

I am running on Java SE 1.8.0_55 (JDK 8 Update 65). I tried it on update 31 as well and getting the same exception. 

```
com.machinepublishers.browser.Browser$Fatal: Method call failed: call
	at com.machinepublishers.jbrowserdriver.JavaFxObject.call(JavaFxObject.java:166)
	at com.machinepublishers.jbrowserdriver.Element$20.perform(Element.java:631)
	at com.machinepublishers.jbrowserdriver.Element$20.perform(Element.java:1)
	at com.machinepublishers.jbrowserdriver.Util$Runner.run(Util.java:96)
	at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:93)
	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodException: com.sun.webkit.dom.HTMLDocumentImpl.call(java.lang.String, [Ljava.lang.Object;)
	at java.lang.Class.getDeclaredMethod(Class.java:2130)
	at com.machinepublishers.jbrowserdriver.JavaFxObject.call(JavaFxObject.java:137)
	... 9 more
```

**Comment by hollingsworthd** [comment] 2015-11-24 17:38
Thanks for the report. What version of jBrowserDriver were you using? Also what page were you trying? You can email me dan@machinepublishers.com if you don't want the link published.

**Comment by hollingsworthd** [comment] 2016-01-12 23:08
Sorry, I can't reproduce this. Please send me the url this happens with. It may have been incidentally fixed in recent versions. Closing issue...

**Closed by hollingsworthd** 2016-01-12 23:08 UTC
Labels: bug
